# Generated by Django 2.1.2 on 2018-11-05 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField()),
                ('name', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(default=None, max_length=150, null=True)),
                ('thl', models.CharField(default=None, max_length=100, null=True)),
                ('com', models.CharField(default=None, max_length=1000, null=True)),
                ('userip', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contactdetails',
            },
        ),
        migrations.CreateModel(
            name='ContactManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField()),
                ('com', models.CharField(default=None, max_length=1000, null=True)),
                ('deyacom', models.CharField(default=None, max_length=500, null=True)),
                ('userip', models.CharField(default=None, max_length=100, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='damage.ContactDetails')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contactmanagement',
            },
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField()),
                ('firstname', models.CharField(default=None, max_length=50)),
                ('lastname', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=100, null=True)),
                ('zipcode', models.CharField(default=None, max_length=6, null=True)),
                ('town', models.CharField(default=None, max_length=50, null=True)),
                ('area', models.CharField(default=None, max_length=50, null=True)),
                ('email', models.EmailField(default=None, max_length=150, null=True)),
                ('thl', models.CharField(default=None, max_length=100, null=True)),
                ('mobile', models.CharField(default=None, max_length=50)),
                ('damageaddress', models.CharField(default=None, max_length=100, null=True)),
                ('damagezipcode', models.CharField(default=None, max_length=6, null=True)),
                ('damagetown', models.CharField(default=None, max_length=50, null=True)),
                ('damagearea', models.CharField(default=None, max_length=50, null=True)),
                ('damagecom', models.CharField(default=None, max_length=1000, null=True)),
                ('lng', models.CharField(default=None, max_length=100, null=True)),
                ('lat', models.CharField(default=None, max_length=100, null=True)),
                ('formatted_address', models.CharField(default=None, max_length=150, null=True)),
                ('userip', models.CharField(default=None, max_length=100, null=True)),
                ('areas', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='damage.Areas')),
            ],
            options={
                'db_table': 'damage',
            },
        ),
        migrations.CreateModel(
            name='DamageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'damagecategory',
            },
        ),
        migrations.CreateModel(
            name='DamageHistoryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField()),
                ('com', models.CharField(default=None, max_length=500, null=True)),
                ('userip', models.CharField(default=None, max_length=100, null=True)),
                ('damage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='damage.Damage')),
            ],
            options={
                'db_table': 'damagehistorystatus',
            },
        ),
        migrations.CreateModel(
            name='DamageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'damagestatus',
            },
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'damagetype',
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deya_aa', models.IntegerField()),
                ('deya_name', models.CharField(max_length=100)),
                ('deya_longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True)),
                ('deya_latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True)),
                ('deya_mapaddress', models.CharField(default=None, max_length=150, null=True)),
                ('google_api_key', models.CharField(default=None, max_length=150, null=True)),
            ],
            options={
                'db_table': 'general',
            },
        ),
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(default=None, max_length=20, null=True)),
                ('longitude', models.CharField(default=None, max_length=20, null=True)),
                ('place_id', models.CharField(default=None, max_length=300, null=True)),
                ('formatted_address', models.CharField(default=None, max_length=250, null=True)),
                ('street_number', models.CharField(default=None, max_length=10, null=True)),
                ('route', models.CharField(default=None, max_length=50, null=True)),
                ('locality', models.CharField(default=None, max_length=50, null=True)),
                ('administrative_area_level_5', models.CharField(default=None, max_length=50, null=True)),
                ('administrative_area_level_4', models.CharField(default=None, max_length=50, null=True)),
                ('administrative_area_level_3', models.CharField(default=None, max_length=50, null=True)),
                ('country', models.CharField(default=None, max_length=50, null=True)),
                ('postal_code', models.CharField(default=None, max_length=10, null=True)),
            ],
            options={
                'db_table': 'locationdetails',
            },
        ),
        migrations.AddField(
            model_name='damagehistorystatus',
            name='damagestatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='damage.DamageStatus'),
        ),
        migrations.AddField(
            model_name='damagehistorystatus',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='damage',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='damage.DamageCategory'),
        ),
        migrations.AddField(
            model_name='damage',
            name='damagestatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='damage.DamageStatus'),
        ),
        migrations.AddField(
            model_name='damage',
            name='damagetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='damage.DamageType'),
        ),
        migrations.AddField(
            model_name='damage',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='damage.LocationDetails'),
        ),
        migrations.AddField(
            model_name='damage',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
