# Generated by Django 2.1.2 on 2018-11-05 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='damage',
            name='category',
        ),
    ]
