# Generated by Django 2.1.2 on 2018-10-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmanagement',
            name='dummy',
        ),
    ]
