# Generated by Django 2.1.2 on 2018-10-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0002_remove_contactmanagement_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='dummy',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
