# Generated by Django 2.1.2 on 2018-11-05 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0002_auto_20181105_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='areas',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='damage.Areas'),
        ),
        migrations.AddField(
            model_name='damage',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='damage.DamageCategory'),
        ),
    ]
