# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0002_auto_20180622_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
