# Generated by Django 2.1.2 on 2018-10-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0003_contactdetails_dummy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdetails',
            old_name='dummy',
            new_name='deya_contact_email',
        ),
    ]
