# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0003_damage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='damage',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='damage.DamageStatus'),
        ),
    ]
