# Generated by Django 2.1.2 on 2018-10-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0004_auto_20181009_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='deya_contact_email',
        ),
    ]
