# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0005_auto_20180623_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deya_aa', models.IntegerField()),
                ('deya_name', models.CharField(max_length=100)),
            ],
        ),
    ]
