# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('damage', '0006_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='damage',
            name='entry_date',
            field=models.DateTimeField(),
        ),
    ]
