# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0007_auto_20180629_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='name',
        ),
        migrations.AddField(
            model_name='damage',
            name='email',
            field=models.EmailField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='damage',
            name='firstname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='damage',
            name='lastname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='damage',
            name='mobile',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='damage',
            name='thl',
            field=models.CharField(default='', max_length=100),
        ),
    ]
