# Generated by Django 2.1.2 on 2018-10-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0008_general_deya_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='deya_contact_email',
        ),
    ]
