# Generated by Django 2.1.2 on 2018-10-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0009_remove_general_deya_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='deya_contact_email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
