# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0009_auto_20180708_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
