# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0010_auto_20180708_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='damage',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='damage',
            name='realadress',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='address',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='area',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='damageaddress',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='damagearea',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='damagecom',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='damagetown',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='damagezipcode',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='email',
            field=models.EmailField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='firstname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='damage',
            name='lastname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='damage',
            name='mobile',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='damage',
            name='thl',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='town',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='zipcode',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
    ]
