# Generated by Django 2.1.2 on 2018-10-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0011_remove_contactdetails_deya_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='DamageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'damagecategory',
            },
        ),
    ]
