# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0011_auto_20180710_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damage',
            old_name='realadress',
            new_name='realaddress',
        ),
    ]
