# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0012_auto_20180710_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='deya_latitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='deya_longitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='deya_mapaddress',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
