# Generated by Django 2.1.2 on 2018-10-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0012_areas_damagecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
