# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0013_auto_20180711_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='deya_latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='deya_longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True),
        ),
    ]
