# Generated by Django 2.1.2 on 2018-10-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0013_auto_20181031_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='code',
            field=models.IntegerField(),
        ),
    ]
