# Generated by Django 2.1.2 on 2018-10-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0014_auto_20181031_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagecategory',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
