# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0014_auto_20180711_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='userip',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
