# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0015_damage_userip'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(default=None, max_length=20, null=True)),
                ('longitude', models.CharField(default=None, max_length=20, null=True)),
                ('place_id', models.CharField(default=None, max_length=50, null=True)),
                ('formatted_address', models.CharField(default=None, max_length=250, null=True)),
                ('street_number', models.CharField(default=None, max_length=10, null=True)),
                ('route', models.CharField(default=None, max_length=50, null=True)),
                ('political', models.CharField(default=None, max_length=50, null=True)),
                ('administrative_area_level_5', models.CharField(default=None, max_length=50, null=True)),
                ('administrative_area_level_4', models.CharField(default=None, max_length=50, null=True)),
                ('administrative_area_level_3', models.CharField(default=None, max_length=50, null=True)),
                ('country', models.CharField(default=None, max_length=50, null=True)),
                ('postal_code', models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='damage',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='damage.LocationDetails'),
        ),
    ]
