# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0016_auto_20180712_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationdetails',
            old_name='political',
            new_name='locality',
        ),
    ]
