# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0017_auto_20180713_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='google_api_key',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
