# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0018_general_google_api_key'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='damagetype',
            table='damagetype',
        ),
    ]
