# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0019_auto_20180719_1235'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='damage',
            table='damage',
        ),
        migrations.AlterModelTable(
            name='damagestatus',
            table='damagestatus',
        ),
        migrations.AlterModelTable(
            name='general',
            table='general',
        ),
    ]
