# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0020_auto_20180719_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdetails',
            name='place_id',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
