# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0020_auto_20180719_1236'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locationdetails',
            table='locationdetails',
        ),
    ]
