# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0021_auto_20180720_1456'),
        ('damage', '0021_auto_20180719_2249'),
    ]

    operations = [
    ]
