# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-24 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0023_auto_20180722_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damage',
            old_name='realaddress',
            new_name='formatted_address',
        ),
        migrations.AlterField(
            model_name='damage',
            name='latitude',
            field=models.CharField(default=None, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='longitude',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
