# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-24 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0024_auto_20180724_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='damage',
            name='longitude',
        ),
        migrations.AddField(
            model_name='damage',
            name='lat',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='damage',
            name='lng',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
