# Generated by Django 2.0.7 on 2018-08-02 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0025_auto_20180724_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='damagestatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='damage.DamageStatus'),
        ),
        migrations.AlterField(
            model_name='damage',
            name='damagetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='damage.DamageType'),
        ),
        migrations.AlterField(
            model_name='damage',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
