# Generated by Django 2.0.7 on 2018-09-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0026_auto_20180802_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField()),
                ('name', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(default=None, max_length=150, null=True)),
                ('thl', models.CharField(default=None, max_length=100, null=True)),
                ('com', models.CharField(default=None, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'contactdetails',
            },
        ),
    ]
