# Generated by Django 2.0.7 on 2018-09-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0027_contactdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='userip',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
